# Generated by Django 2.0.4 on 2018-04-07 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('b_value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date', models.DateField(default=datetime.date.today)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sites.Site')),
            ],
        ),
    ]
